version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mikelegal:
    image: mikelegal-image
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - redis
    restart: always
